insert into todos values (1, "I want to eat pizza", "NO");
insert into todos values (2, "Play Minecraft", "NO");
insert into todos values (3, "Halloween Party", "YES");
insert into todos values (4, "Make Pumpkins", "NO");
insert into todos values (5, "Do Project", "YES");

insert into todos values 
    (6, "Make Art", "NO"), 
    (7, "Color", "NO"),
    (8, "Go Outside", "YES"),
    (9, "Get lots of cupcakes", "YES"),
    (10, "Finish Cupcakes", "YES"),
    (11, "Plant a tree", "YES"),
    (12, "Read to it", "YES"),
    (13, "Tell it about what the world is", "NO"),
    (14, "Get a blanket for it", "NO"),
    (15, "Wait until it grows", "NO"),
    (16, "Go Swimming", "YES"),
    (17, "Play with toys", "YES"),
    (18, "Make a toy for the tree", "NO"),
    (19, "Eat Bagel", "NO"),
    (20, "Read a book", "YES"),
    (21, "Make a fort", "YES"),
    (22, "Play more", "NO"),
    (23, "Sleep", "YES"),
    (24, "Watch TV", "NO"),
    (25, "Go Outside", "NO"),
    (26, "Bake Cookies", "YES"),
    (27, "Put Icing", "NO"),
    (28, "Add Rainbow Sprinkles", "NO"),
    (29, "Eat them", "YES"),
    (30, "Share some", "YES"),
    (31, "Make Lemonade", "YES"),
    (32, "Drink Lemonade", "YES"),
    (33, "Drink some kind of other juice", "NO"),
    (34, "Get Chocolate Ice Cream", "YES"),
    (35, "Get Vanilla Ice Cream", "NO"),
    (36, "Get Strawberry Ice Cream", "NO"),
    (37, "Get Blueberry Ice Cream", "YES"),
    (38, "Share a fourth of each to four other people", "YES"),
    (39, "Do nothing for a whole hour", "YES"),
    (40, "Make a dirt man", "YES"),
    (41, "Watch the sun for a day", "YES"),
    (42, "Look at everything outside from inside", "YES"),
    (43, "Sleep", "NO"),
    (44, "Wake Up", "NO"),
    (45, "Play a board game", "NO"),
    (46, "Play a card game", "YES"),
    (47, "Watch TV", "NO"),
    (48, "Do minecraft", "YES"),
    (49, "Bake cookies", "YES"),
    (50, "Bake cakes", "YES"),
    (51, "Bake cupcakes", "NO"),
    (52, "Bake brownies", "YES"),
    (53, "Bake chocolate", "YES"),
    (54, "Ice them all", "YES"),
    (55, "Sprinkle all of them", "YES"),
    (56, "Eat cookies", "YES"),
    (57, "Eat cakes", "YES"),
    (58, "Eat cupcakes", "YES"),
    (59, "Eat brownies", "NO"),
    (60, "Eat chocolate", "NO"),
    (61, "Do nothing", "NO"),
    (62, "Wait until the day is done", "YES"),
    (63, "Go to sleep", "NO"),
    (64, "Wake up", "NO"),
    (65, "Eat breakfast", "NO"),
    (66, "Watch TV", "NO"),
    (67, "Do Minecraft", "NO"),
    (68, "Go talk to tree", "YES"),
    (69, "Take a nap", "YES"),
    (70, "Eat ICE CREAM!!", "YES"),
    (71, "But, share some", "YES"),
    (72, "Get MUCH MORE", "YES"),
    (73, "Sleep", "YES"),
    (74, "Wake Up", "NO"),
    (75, "Do Nothing", "NO"),
    (76, "Look outside", "YES"),
    (77, "Go Outside", "YES"),
    (78, "Play at the park", "NO"),
    (79, "Swim at the swimming pool", "NO"),
    (80, "Sleep", "YES"),
    (81, "Wake Up", "YES"),
    (82, "Eat Pizza", "NO"),
    (83, "Bounce on the ball", "NO"),
    (84, "Play with the tree", "NO"),
    (85, "Make art", "YES"),
    (86, "Make a craft", "YES"),
    (87, "Sleep", "YES"),
    (88, "Wake Up", "YES"),
    (89, "Do Project", "NO"),
    (90, "Do Nothing", "YES"),
    (91, "Watch TV", "YES"),
    (92, "Play Minecraft", "YES"),
    (93, "Bake Cakes", "YES"),
    (94, "Bake Muffins", "NO"),
    (95, "Bake Cupcakes", "NO"),
    (96, "Bake Pies", "YES"),
    (97, "Eat them", "NO"),
    (98, "Go to the park", "YES"),
    (99, "Make a swing", "NO"),
    (100, "Sleep", "NO")
    ;
